apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: wildcard-prod
 namespace: cert-manager
 labels:
   "use-cloudflare-solver": "true"
spec:
 commonName: '*.iceo.co'
 secretName: wildcard-prod-tls
 issuerRef:
   name: letsencrypt-prod
   kind: ClusterIssuer
 dnsNames:
    - 'iceo.co'
    - '*.iceo.co'
