apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: blazkamil@outlook.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
            class: nginx
    - dns01:
          cloudflare:
            email: {{ .Values.cloudflare_email  }}
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
      selector:
          matchLabels:
            "use-cloudflare-solver": "true"
---

apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: {{ .Values.cloudflare_token  }}
