---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "network-policy.name" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  podSelector:
    matchLabels:
      {{- include "commonLabels" . | indent 6 }}
  policyTypes:
    - Egress
  egress:
    - to:
      - ipBlock:
          cidr: {{ .Values.whitelist.cidr }}
      ports:
        - port: 80
          protocol: TCP
        - port: 443
          protocol: TCP
